'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('./lib/api');

module.exports = {
  version: require('./package.json').version,
  platformVersion: require('zapier-platform-core').version,

  authentication: {
    type: 'custom',
    fields: [
      {
        "key": "api_key",
        "label": "API Key",
        "type": "password",
        "required": true,
        "helpText": "Create a key at [pdfrender.dev](https://pdfrender.dev/go/zapier?to=/app/api-keys)."
      },
    ],
    test: api.testAuth,
  },

  beforeRequest: [api.addApiKey],

  creates: {
    get_me: require('./creates/get_me'),
    render_html_to_pdf: require('./creates/render_html_to_pdf'),
  },
};
