'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "GET",
  "path": "/v1/me",
  "body": null,
  "output": "json",
  "fields": []
};

const DEFINITION = {
  "key": "get_me",
  "noun": "pdfrender",
  "display": {
    "label": "Your plan, remaining requests, and remaining credits",
    "description": "Check where you stand before a call fails."
  },
  "operation": {
    "inputFields": [],
    "sample": {
      "tier": "sample",
      "is_keyed": true,
      "rate_limit": {},
      "credits": {},
      "features": []
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
