'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "POST",
  "path": "/v1/render",
  "body": "json",
  "output": "binary",
  "fields": [
    {
      "name": "html",
      "location": "json",
      "type": "string"
    },
    {
      "name": "filename",
      "location": "json",
      "type": "string"
    },
    {
      "name": "pdf_variant",
      "location": "json",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "render_html_to_pdf",
  "noun": "pdfrender",
  "display": {
    "label": "Render an HTML document to a PDF",
    "description": "Send an HTML document and get the PDF back as a download."
  },
  "operation": {
    "inputFields": [
      {
        "key": "html",
        "label": "Html",
        "required": true,
        "type": "string",
        "helpText": "The HTML document, up to 2 MB. Inline images, fonts and CSS as data: URIs; external resources are not loaded. JavaScript is not run."
      },
      {
        "key": "filename",
        "label": "Filename",
        "required": false,
        "type": "string",
        "helpText": "Filename of the downloaded PDF. Characters other than A–Z, a–z, 0–9, `.`, `_` and `-` become `_`, and `.pdf` is added if missing.",
        "default": "document.pdf"
      },
      {
        "key": "pdf_variant",
        "label": "Pdf variant",
        "required": false,
        "type": "string",
        "helpText": "Write the PDF as PDF/A-2b or PDF/A-3b, for archiving. Paid plans only: without one, the call gets 403 `feature_not_available` with an `upgrade_url`. Leave it out for a regular PDF.",
        "choices": [
          "pdf/a-2b",
          "pdf/a-3b"
        ]
      }
    ],
    "sample": {
      "file": "SAMPLE FILE",
      "content_type": "application/pdf"
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
