import { defineConfig } from '@hey-api/openapi-ts';

// Generated by listing-sync. The client is re-exported from the package
// entry so callers can set their API key once (client.setConfig).
export default defineConfig({
  input: '../openapi.sdk.json',
  output: 'src',
  plugins: [
    { name: '@hey-api/client-fetch', includeInEntry: true },
    '@hey-api/typescript',
    '@hey-api/sdk',
  ],
});
