/* globals describe, expect, test */
'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
// Live calls need a key (API_KEY=... npm test) and spend its credits; a
// binary answer is stashed as a Zapier file, which also needs ZAPIER_DEPLOY_KEY.
const zapier = require('zapier-platform-core');

const App = require('../index');

const appTester = zapier.createAppTester(App);
zapier.tools.env.inject();

const live = process.env.API_KEY ? test : test.skip;
const liveFile = process.env.API_KEY && process.env.ZAPIER_DEPLOY_KEY ? test : test.skip;
const authData = { api_key: process.env.API_KEY };

describe('authentication', () => {
  live('accepts the key', async () => {
    const result = await appTester(App.authentication.test, { authData });
    expect(result).toBeTruthy();
  });
});

describe('creates', () => {
  live('get_me', async () => {
    const inputData = {};
    const result = await appTester(App.creates.get_me.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  liveFile('render_html_to_pdf', async () => {
    const inputData = {
      "html": "<!doctype html>\n<style>\n@page { size: A4; margin: 22mm }\nbody { font: 11pt/1.5 sans-serif; color: #1c2024 }\ntable { width: 100%; border-collapse: collapse }\nth { text-align: left; border-bottom: 2px solid #1c2024 }\ntd { padding: 3mm 0; border-bottom: 1px solid #e3e6ea }\n</style>\n<h1>Invoice 2026-041</h1>\n<p>Northwind Studio · Due Sep 30, 2026</p>\n<table>\n  <thead><tr><th>Description</th><th>Qty</th><th>Amount</th></tr></thead>\n  <tbody>\n    <tr><td>Design retainer, September</td><td>1</td><td>1,800.00</td></tr>\n    <tr><td>Illustration, cover set</td><td>6</td><td>720.00</td></tr>\n  </tbody>\n</table>\n",
      "filename": "invoice.pdf"
    };
    const result = await appTester(App.creates.render_html_to_pdf.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });
});
