"""pdfrender credentials. Generated by listing-sync (infra scripts/listing_sync/connectors/dify.py); edits are overwritten."""

from typing import Any

import httpx
from dify_plugin import ToolProvider
from dify_plugin.errors.tool import ToolProviderCredentialValidationError

from tools._client import get


class PdfrenderProvider(ToolProvider):
    def _validate_credentials(self, credentials: dict[str, Any]) -> None:
        try:
            response = get(credentials, '/v1/me')
        except httpx.HTTPError as err:
            msg = f"The pdfrender API is unreachable: {err}"
            raise ToolProviderCredentialValidationError(msg) from err
        if response.status_code in (401, 403):
            msg = "The pdfrender API rejected this API key."
            raise ToolProviderCredentialValidationError(msg)
        if response.status_code != 200:
            msg = f"The pdfrender API answered {response.status_code}."
            raise ToolProviderCredentialValidationError(msg)
