"""The HTTP code every pdfrender tool shares. Generated by listing-sync (infra scripts/listing_sync/connectors/dify.py); edits are overwritten."""

import json
import mimetypes
import re
import urllib.parse

import httpx

BASE_URL = 'https://api.pdfrender.dev'
AUTH_HEADER = 'X-API-Key'
CREDENTIAL = 'x_api_key'
USER_AGENT = 'pdfrender-dify/1.0.2'
TIMEOUT = 240
TITLE = 'pdfrender'


class ApiError(Exception):
    """The API answered with an error status."""


def _headers(credentials):
    return {AUTH_HEADER: credentials.get(CREDENTIAL, ""), "User-Agent": USER_AGENT}


def get(credentials, path):
    return httpx.get(BASE_URL + path, headers=_headers(credentials), timeout=TIMEOUT)


def _text(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _value(field, value):
    kind = field["type"]
    if kind in ("object", "array") and field["location"] == "json":
        return json.loads(value) if isinstance(value, str) else value
    if kind == "integer" and isinstance(value, float) and value.is_integer():
        return int(value)
    return value


def request(credentials, operation, params):
    """Send one operation with the tool parameters it was given."""
    path, query, body, data, files = operation["path"], [], {}, {}, {}
    for field in operation["fields"]:
        name, where = field["name"], field["location"]
        value = params.get(name)
        if value is None or value == "" or value == []:
            continue
        value = _value(field, value)
        if where == "path":
            path = path.replace("{" + name + "}", urllib.parse.quote(_text(value), safe=""))
        elif where == "query" and field["type"] == "array":
            items = value if isinstance(value, list) else str(value).split(",")
            query += [(name, _text(v).strip()) for v in items if _text(v).strip()]
        elif where == "query":
            query.append((name, _text(value)))
        elif where == "json":
            body[name] = value
        elif where == "form":
            data[name] = _text(value)
        else:
            mime = value.mime_type or "application/octet-stream"
            files[name] = (value.filename or name, value.blob, mime)
    send = {}
    if operation["body"] == "json":
        send["json"] = body
    elif data:
        send["data"] = data
    if files:
        send["files"] = files
    return httpx.request(
        operation["method"],
        BASE_URL + path,
        params=query,
        headers=_headers(credentials),
        timeout=TIMEOUT,
        **send,
    )


def _error(response):
    try:
        detail = response.json().get("detail", response.text)
    except (ValueError, AttributeError):
        detail = response.text
    if not isinstance(detail, str):
        detail = json.dumps(detail)
    return f"The {TITLE} API answered {response.status_code}: {detail[:1000]}"


def _filename(response, mime):
    match = re.search(r'filename="?([^";]+)"?', response.headers.get("content-disposition", ""))
    if match:
        return match.group(1)
    return "result" + (mimetypes.guess_extension(mime) or "")


def call(tool, operation, params):
    """Run the operation and yield its answer: JSON as a JSON message,
    text and XML as text, anything else as a file."""
    response = request(tool.runtime.credentials, operation, params)
    if response.status_code >= 400:
        raise ApiError(_error(response))
    mime = response.headers.get("content-type", "").split(";")[0].strip().lower()
    if mime == "application/json" or mime.endswith("+json"):
        answer = response.json()
        yield tool.create_json_message(answer if isinstance(answer, (dict, list)) else {"result": answer})
    elif mime.startswith("text/") or mime == "application/xml" or mime.endswith("+xml"):
        yield tool.create_text_message(response.text)
    else:
        mime = mime or "application/octet-stream"
        meta = {"mime_type": mime, "filename": _filename(response, mime)}
        yield tool.create_blob_message(response.content, meta=meta)
