"""pdfrender: Render HTML to PDF. Generated by listing-sync (infra scripts/listing_sync/connectors/dify.py); edits are overwritten."""

from collections.abc import Generator
from typing import Any

from dify_plugin import Tool
from dify_plugin.entities.tool import ToolInvokeMessage

from tools._client import call

OPERATION = {
    "method": "POST",
    "path": "/v1/render",
    "body": "json",
    "fields": [
        {
            "name": "html",
            "location": "json",
            "type": "string"
        },
        {
            "name": "filename",
            "location": "json",
            "type": "string"
        },
        {
            "name": "pdf_variant",
            "location": "json",
            "type": "string"
        }
    ]
}


class RenderHtmlToPdfTool(Tool):
    def _invoke(self, tool_parameters: dict[str, Any]) -> Generator[ToolInvokeMessage]:
        yield from call(self, OPERATION, tool_parameters)
