// Generated by listing-sync from https://api.pdfrender.dev/openapi.json — do not edit.
import type {
	IDataObject,
	IExecuteFunctions,
	IHttpRequestMethods,
	IN8nHttpFullResponse,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
	JsonObject,
} from 'n8n-workflow';
import {
	jsonParse,
	NodeApiError,
	NodeConnectionTypes,
	NodeOperationError,
	sleep,
} from 'n8n-workflow';

const BASE_URL = 'https://api.pdfrender.dev';
const CREDENTIAL = 'pdfrenderApi';
const POLL_SECONDS = 5;
const POLL_LIMIT = 360;

type Location = 'path' | 'query' | 'json' | 'form' | 'file';

interface ApiField {
	name: string;
	param: string;
	location: Location;
	type: string;
	required: boolean;
}

interface ApiOperation {
	method: IHttpRequestMethods;
	path: string;
	body: 'none' | 'json' | 'form';
	fields: ApiField[];
	job?: { poll: string; result: string };
}

function jsonValue(value: unknown): unknown {
	return typeof value === 'string' ? jsonParse(value) : value;
}

async function request(
	ctx: IExecuteFunctions,
	method: IHttpRequestMethods,
	path: string,
	qs: IDataObject = {},
	body?: FormData | IDataObject,
): Promise<IN8nHttpFullResponse> {
	return (await ctx.helpers.httpRequestWithAuthentication.call(ctx, CREDENTIAL, {
		method,
		url: BASE_URL + path,
		qs,
		arrayFormat: 'repeat',
		body,
		encoding: 'arraybuffer',
		returnFullResponse: true,
	})) as IN8nHttpFullResponse;
}

async function send(
	ctx: IExecuteFunctions,
	op: ApiOperation,
	i: number,
): Promise<IN8nHttpFullResponse> {
	const extra = ctx.getNodeParameter('additionalFields', i, {}) as IDataObject;
	const binary = ctx.getInputData()[i].binary ?? {};
	let path = op.path;
	const qs: IDataObject = {};
	const json: IDataObject = {};
	const form = new FormData();
	for (const field of op.fields) {
		const topLevel = field.required || field.location === 'file';
		const value = topLevel ? ctx.getNodeParameter(field.param, i, '') : extra[field.param];
		if (value === undefined || value === '') continue;
		if (field.location === 'file') {
			const property = String(value);
			if (!field.required && !binary[property]) continue;
			const meta = ctx.helpers.assertBinaryData(i, property);
			const buffer = await ctx.helpers.getBinaryDataBuffer(i, property);
			form.append(
				field.name,
				new Blob([new Uint8Array(buffer)], { type: meta.mimeType }),
				meta.fileName ?? field.name,
			);
		} else if (field.location === 'path') {
			path = path.replace(`{${field.name}}`, encodeURIComponent(String(value)));
		} else if (field.location === 'query') {
			qs[field.name] =
				field.type === 'array'
					? String(value)
							.split(',')
							.map((v) => v.trim())
							.filter((v) => v)
					: (value as IDataObject[keyof IDataObject]);
		} else if (field.location === 'json') {
			json[field.name] = (
				field.type === 'object' || field.type === 'array' ? jsonValue(value) : value
			) as IDataObject[keyof IDataObject];
		} else {
			form.append(field.name, String(value));
		}
	}
	const body = op.body === 'form' ? form : op.body === 'json' ? json : undefined;
	return await request(ctx, op.method, path, qs, body);
}

function onePath(path: string, id: string): string {
	return path.replace(/\{[^}]+\}/, encodeURIComponent(id));
}

async function decode(
	ctx: IExecuteFunctions,
	response: IN8nHttpFullResponse,
	i: number,
): Promise<INodeExecutionData> {
	const header = response.headers['content-type'];
	const mimeType = String(Array.isArray(header) ? header[0] : (header ?? '')).split(';')[0].trim();
	const data = Buffer.from(response.body as ArrayBuffer);
	if (mimeType === 'application/json' || mimeType.endsWith('+json')) {
		const parsed = jsonParse<unknown>(data.toString('utf8'));
		const item =
			parsed && typeof parsed === 'object' && !Array.isArray(parsed)
				? (parsed as IDataObject)
				: ({ data: parsed } as IDataObject);
		return { json: item, pairedItem: { item: i } };
	}
	if (mimeType.startsWith('text/') || mimeType.endsWith('xml')) {
		return { json: { data: data.toString('utf8'), mimeType }, pairedItem: { item: i } };
	}
	const disposition = String(response.headers['content-disposition'] ?? '');
	const fileName = /filename="?([^";]+)"?/.exec(disposition)?.[1];
	const file = await ctx.helpers.prepareBinaryData(data, fileName, mimeType || undefined);
	return {
		json: { fileName: file.fileName, mimeType: file.mimeType, fileSize: file.fileSize },
		binary: { data: file },
		pairedItem: { item: i },
	};
}

async function runJob(
	ctx: IExecuteFunctions,
	job: { poll: string; result: string },
	submitted: IDataObject,
	i: number,
): Promise<IN8nHttpFullResponse> {
	const id = String(submitted.job_id ?? submitted.id ?? '');
	const poll = OPERATIONS[job.poll];
	const result = OPERATIONS[job.result];
	for (let attempt = 0; attempt < POLL_LIMIT; attempt++) {
		await sleep(POLL_SECONDS * 1000);
		const state = (await decode(ctx, await request(ctx, poll.method, onePath(poll.path, id)), i))
			.json;
		if (state.status === 'succeeded') {
			return await request(ctx, result.method, onePath(result.path, id));
		}
		if (state.status === 'failed') {
			throw new NodeOperationError(ctx.getNode(), `Job ${id} failed: ${String(state.error ?? '')}`, {
				itemIndex: i,
			});
		}
	}
	throw new NodeOperationError(ctx.getNode(), `Job ${id} did not finish in time`, { itemIndex: i });
}

const OPERATIONS: Record<string, ApiOperation> = {
	get_me: {
		method: 'GET',
		path: '/v1/me',
		body: 'none',
		fields: [],
	},
	render_html_to_pdf: {
		method: 'POST',
		path: '/v1/render',
		body: 'json',
		fields: [
			{
				name: 'html',
				param: 'html',
				location: 'json',
				type: 'string',
				required: true,
			},
			{
				name: 'filename',
				param: 'filename',
				location: 'json',
				type: 'string',
				required: false,
			},
			{
				name: 'pdf_variant',
				param: 'pdfVariant',
				location: 'json',
				type: 'string',
				required: false,
			},
		],
	},
};

export class Pdfrender implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'pdfrender',
		name: 'pdfrender',
		icon: {
			light: 'file:../../icons/pdfrender.svg',
			dark: 'file:../../icons/pdfrender.svg',
		},
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: 'HTML and CSS to PDF API and MCP server. WeasyPrint with page headers, footers and page numbers, no headless browser. Hosted in Germany.',
		defaults: {
			name: 'pdfrender',
		},
		usableAsTool: true,
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		credentials: [
			{
				name: 'pdfrenderApi',
				required: true,
			},
		],
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				options: [
					{
						name: 'Account',
						value: 'account',
					},
					{
						name: 'Pdfrender',
						value: 'pdfrender',
					},
				],
				default: 'pdfrender',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: {
					show: {
						resource: ['account'],
					},
				},
				options: [
					{
						name: 'Get Me',
						value: 'get_me',
						description: 'Your plan, remaining requests, and remaining credits',
						action: 'Get me',
					},
				],
				default: 'get_me',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: {
					show: {
						resource: ['pdfrender'],
					},
				},
				options: [
					{
						name: 'Render HTML To PDF',
						value: 'render_html_to_pdf',
						description: 'Render an HTML document to a PDF',
						action: 'Render HTML to PDF',
					},
				],
				default: 'render_html_to_pdf',
			},
			{
				displayName: 'HTML',
				name: 'html',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						resource: ['pdfrender'],
						operation: ['render_html_to_pdf'],
					},
				},
				description: 'The HTML document, up to 2 MB. Inline images, fonts and CSS as data: URIs; external resources are not loaded. JavaScript is not run.',
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['pdfrender'],
						operation: ['render_html_to_pdf'],
					},
				},
				options: [
					{
						displayName: 'Filename',
						name: 'filename',
						type: 'string',
						default: 'document.pdf',
						description: 'Filename of the downloaded PDF. Characters other than A–Z, a–z, 0–9, \'.\', \'_\' and \'-\' become \'_\', and \'.pdf\' is added if missing.',
					},
					{
						displayName: 'PDF Variant',
						name: 'pdfVariant',
						type: 'options',
						options: [
							{
								name: 'PDF A 2b',
								value: 'pdf/a-2b',
							},
							{
								name: 'PDF A 3b',
								value: 'pdf/a-3b',
							},
						],
						default: 'pdf/a-2b',
						description: 'Write the PDF as PDF/A-2b or PDF/A-3b, for archiving. Paid plans only: without one, the call gets 403 \'feature_not_available\' with an \'upgrade_url\'. Leave it out for a regular PDF.',
					},
				],
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			try {
				const op = OPERATIONS[this.getNodeParameter('operation', i) as string];
				let response = await send(this, op, i);
				if (op.job) {
					const submitted = (await decode(this, response, i)).json;
					response = await runJob(this, op.job, submitted, i);
				}
				out.push(await decode(this, response, i));
			} catch (error) {
				if (this.continueOnFail()) {
					out.push({ json: { error: (error as Error).message }, pairedItem: { item: i } });
					continue;
				}
				throw new NodeApiError(this.getNode(), error as JsonObject, { itemIndex: i });
			}
		}
		return [out];
	}
}
