project_name_override: "pdfrender"
package_name_override: "pdfrender"
package_version_override: "1.0.1"
content_type_overrides:
  "application/pdf": "application/octet-stream"
  "application/xml": "application/octet-stream"
