'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
// The one place requests are made; each creates/<key>.js describes its
// operation (method, path, fields, output) and calls into here.
const http = require('http');
const https = require('https');
const FormData = require('form-data');

const BASE_URL = "https://api.pdfrender.dev";
const AUTH_HEADER = "X-API-Key";
const ME_PATH = "/v1/me";
const KEY_LINK = "https://pdfrender.dev/go/zapier?to=/app/api-keys";

// beforeRequest: every request carries the connection's key.
const addApiKey = (request, z, bundle) => {
  if (bundle.authData && bundle.authData.api_key) {
    request.headers = request.headers || {};
    request.headers[AUTH_HEADER] = bundle.authData.api_key;
  }
  return request;
};

const testAuth = async (z) => {
  const response = await z.request({ url: BASE_URL + ME_PATH });
  if (response.data && response.data.is_keyed === false) {
    throw new z.errors.Error(
      `The API key was not accepted. Create one at ${KEY_LINK}`,
      'AuthenticationError',
      401,
    );
  }
  return response.data;
};

// A file input arrives as a URL (Zapier's example-apps/files): stream it,
// paused until the form is assembled, following redirects.
const download = (url, hops = 5) =>
  new Promise((resolve, reject) => {
    const client = url.startsWith('http:') ? http : https;
    client
      .get(url, (res) => {
        res.pause();
        const status = res.statusCode;
        if (status >= 300 && status < 400 && res.headers.location && hops > 0) {
          res.resume();
          resolve(download(new URL(res.headers.location, url).toString(), hops - 1));
        } else if (status !== 200) {
          res.resume();
          reject(new Error(`Downloading the file failed: HTTP ${status}`));
        } else {
          resolve(res);
        }
      })
      .on('error', reject);
  });

const present = (value) => value !== undefined && value !== null && value !== '';

const coerce = (field, value) => {
  switch (field.type) {
    case 'integer':
    case 'number':
      return Number(value);
    case 'boolean':
      return value === true || ['true', 'yes', '1'].includes(String(value).toLowerCase());
    case 'object':
    case 'array':
      if (typeof value !== 'string') return value;
      try {
        return JSON.parse(value);
      } catch (err) {
        throw new Error(`${field.name} must be JSON: ${err.message}`);
      }
    default:
      return value;
  }
};

const output = async (z, op, response) => {
  const type = response.headers.get('content-type') || '';
  if (op.output === 'binary') {
    return { file: await z.stashFile(response), content_type: type };
  }
  if (/[/+]json\b/.test(type)) {
    const data = response.data;
    if (Array.isArray(data)) return { items: data };
    return data !== null && typeof data === 'object' ? data : { value: data };
  }
  return { text: response.content, content_type: type };
};

// Call one operation with `input` (field name -> value).
const call = async (z, op, input) => {
  let path = op.path;
  const query = new URLSearchParams();
  const json = {};
  const form = op.body === 'form' ? new FormData() : null;
  const streams = [];
  for (const field of op.fields) {
    const value = input[field.name];
    if (!present(value)) continue;
    if (field.location === 'path') {
      path = path.replace(`{${field.name}}`, encodeURIComponent(value));
    } else if (field.location === 'query') {
      // An array is sent as repeated keys: ?code=a&code=b
      for (const item of Array.isArray(value) ? value : [value]) {
        query.append(field.name, String(item));
      }
    } else if (field.location === 'json') {
      json[field.name] = coerce(field, value);
    } else if (field.location === 'file') {
      const stream = await download(value);
      streams.push(stream);
      form.append(field.name, stream);
    } else {
      form.append(field.name, String(value));
    }
  }
  streams.forEach((stream) => stream.resume());
  const qs = query.toString();
  const response = await z.request({
    method: op.method,
    url: BASE_URL + path + (qs ? `?${qs}` : ''),
    body: op.body === 'json' ? json : form || undefined,
    raw: op.output === 'binary',
  });
  return output(z, op, response);
};

// performResume of a job: the callback carries {job_id, status, result, error};
// a succeeded job's result is fetched with the job's result operation.
const resume = async (z, bundle, result) => {
  const job = { ...bundle.outputData, ...bundle.cleanedRequest };
  if (job.status !== 'succeeded') {
    throw new z.errors.Error(
      `The job ${job.job_id} ${job.status}: ${job.error || 'no details'}`,
      'JobFailed',
      400,
    );
  }
  return { job_id: job.job_id, ...(await call(z, result, job)) };
};

module.exports = { BASE_URL, AUTH_HEADER, KEY_LINK, addApiKey, testAuth, call, resume };
