#!/usr/bin/env bash
# Generated by listing-sync (infra scripts/listing_sync/connectors/make.py); edits are overwritten.
# Pushes this folder to the Make custom app named in app.json: the app's
# label/description/theme and base, the API-key connection (created when
# missing, matched by label: Make names it), every module (created when
# missing) with its sections, the module groups and the help. Needs make-cli,
# jq, MAKE_API_KEY and MAKE_ZONE (e.g. eu2.make.com). Make validates each
# section as it is set; the first rejection stops the run.
set -euo pipefail
cd "$(dirname "$0")"

app=$(jq -r .name app.json)
version=$(jq -r .version app.json)
if [ -z "$app" ]; then
  echo "::error::app.json has no Make app name: set [app.<app>.params.make] app" >&2
  exit 1
fi
if ! make-cli sdk-apps get --name="$app" --version="$version" >/dev/null; then
  echo "::error::Make app $app version $version not found in $MAKE_ZONE: create it once (make-cli sdk-apps create) and record its name" >&2
  exit 1
fi

make-cli sdk-apps update --name="$app" --version="$version" \
  --label="$(jq -r .label app.json)" \
  --description="$(jq -r .description app.json)" \
  --theme="$(jq -r .theme app.json)" >/dev/null
make-cli sdk-apps set-section --name="$app" --version="$version" \
  --section=base --body="$(cat base.imljson)"

label=$(jq -r .connection.label app.json)
connection=$(make-cli sdk-connections list --app-name="$app" |
  jq -r --arg label "$label" 'first(.[] | select(.label == $label) | .name) // empty')
if [ -z "$connection" ]; then
  connection=$(make-cli sdk-connections create --app-name="$app" \
    --type="$(jq -r .connection.type app.json)" --label="$label" | jq -r .name)
fi
for section in parameters api; do
  make-cli sdk-connections set-section --connection-name="$connection" \
    --section="$section" --body="$(cat "connection/$section.imljson")"
done

existing=$(make-cli sdk-modules list --app-name="$app" --app-version="$version" | jq -r '.[].name')
# Module names are letters and digits (make.py module_name).
for name in $(jq -r '.modules[].name' app.json); do
  module=$(jq -c --arg name "$name" '.modules[] | select(.name == $name)' app.json)
  if ! grep -qxF "$name" <<<"$existing"; then
    make-cli sdk-modules create --app-name="$app" --app-version="$version" \
      --name="$name" --type-id="$(jq -r .typeId <<<"$module")" \
      --label="$(jq -r .label <<<"$module")" \
      --description="$(jq -r .description <<<"$module")" \
      --module-init-mode=blank >/dev/null
  fi
  make-cli sdk-modules update --app-name="$app" --app-version="$version" \
    --module-name="$name" --connection="$connection" \
    --label="$(jq -r .label <<<"$module")" \
    --description="$(jq -r .description <<<"$module")" >/dev/null
  # Static parameters are for triggers only: an action keeps them empty.
  make-cli sdk-modules set-section --app-name="$app" --app-version="$version" \
    --module-name="$name" --section=parameters --body='[]'
  for section in api expect interface samples; do
    make-cli sdk-modules set-section --app-name="$app" --app-version="$version" \
      --module-name="$name" --section="$section" \
      --body="$(cat "modules/$name/$section.imljson")"
  done
done

make-cli sdk-apps set-section --name="$app" --version="$version" \
  --section=groups --body="$(cat groups.json)"
make-cli sdk-apps set-docs --name="$app" --version="$version" --docs="$(cat help.md)"
echo "Pushed $(jq '.modules | length' app.json) modules to Make app $app."
